### ISSUE TITLE
Migrating to IsaacLab

### ISSUE THREAD

**Issue by ju-kreber** [tud-airlab/mppi-isaac#58]
Dear authors,

apparently, nvidia has shut down access to IsaacGym. It cannot be downloaded anymore from https://developer.nvidia.com/isaac-gym although the web page still says otherwise.

I find this work very interesting and would like to build on it, but given this move by nvidia that seems to be impossible at the moment. Apparently, the only officially supported software as of now is [IsaacLab](https://github.com/isaac-sim/IsaacLab).

So I'd like to ask, are to planning to migrate this project to IsaacLab? If so, could you already specify a rough time frame?

Thanks in advance!

**Comment by cpezzato** [comment]
Hi @ju-kreber, 

Just read about it, a pity Nvidia stopped support. However, using your link I just managed to download isaacgym, so it should be possible for you as well to do so. I can share the download otherwise through some other means. 

We are not planning to migrate to isaac-lab, unfortunately the project on which we developed mppi-isaac is not anymore running and most of the team, me included, has moved to a different position. 

If you are interested in embarking on this journey yourself we can provide input but not actively developing. (@c-salmi @eliatrevisan @maxspahn)

**Comment by ju-kreber** [comment]
Thanks a lot for the reply!

Fortunately, nvidia put the link to IsaacGym back up, claiming it was "accidentally removed".
So now I could download the software and get your examples running.

Thank you also for the update on the project. I will experiment a bit and maybe get back to you regarding IsaacLab. :)
